#!/usr/bin/env bash


sleep 1.2
result=$(hyprctl dispatch pin active)
if [ "$result" == "ok" ]; then
    hyprctl notify 5 10000 "rgb(ff0000)" "fontsize:20 Floating Window [Un]Pinned"
else
    hyprctl notify 0 10000 "rgb(ff0000)" "fontsize:20 $result"
fi